Section "ServerFlags"
    Option "AutoAddDevices"    "false"
    Option "AutoEnableDevices" "false"
    Option "AllowEmptyInput"   "true"
<<<<<<< HEAD
=======
    Option "BlankTime"         "0"
    Option "StandbyTime"       "0"
    Option "SuspendTime"       "0"
    Option "OffTime"           "0"
>>>>>>> V_H
EndSection

Section "Device"
    Identifier "NvidiaGPU"
    Driver     "nvidia"
EndSection

Section "Monitor"
    Identifier  "DP0"
    VendorName  "Unknown"
    ModelName   "2560x1440"
    Modeline    "2560x1440_60.00" 241.50 2560 2608 2640 2720 1440 1443 1448 1481 -hsync +vsync
    Option      "PreferredMode"   "2560x1440_60.00"
    Option      "ConnectedMonitor" "DP-0"
<<<<<<< HEAD
=======
    Option      "DPMS"            "false"
>>>>>>> V_H
EndSection

Section "Screen"
    Identifier   "Screen0"
    Device       "NvidiaGPU"
    Monitor      "DP0"
    DefaultDepth 24
    SubSection "Display"
        Depth  24
        Modes  "2560x1440_60.00"
    EndSubSection
EndSection

Section "ServerLayout"
    Identifier "JetsonLayout"
    Screen     0 "Screen0" 0 0
EndSection
